version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app                 # Mount code into container
    environment:
      - DEBUG=1                # Enable Django debug mode
    command: python manage.py runserver 0.0.0.0:8000
