version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
    restart: always
    command: gunicorn expense_tracker.wsgi:application --bind 0.0.0.0:8000
